name             'jenkins'
maintainer       'T-Mobile'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Configures jenkins for Jazz'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.0'
depends          'poise-python'
depends          'maven'
depends          'nodejs'
depends          'cloudcli'
